<!DOCTYPE html>
<html lang="es-mx">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Science Technology Engineerig & Mathematics</title>
    <link rel="stylesheet" href="">
    <link rel="stylesheet" href="css/estilos.css">
    <link rel="stylesheet" href="css/menu.css"/>
    <link rel="stylesheet" href="css/problema.css"/>
    <link href="https://fonts.googleapis.com/css?family=Rambla" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    </head>

<body>
   <section id="contenedor">
    <header id="gridHeader">
    <center><h1>Science Technology Engineerig & Mathematics</h1></center>
    <center><h2>Resolver problemas de Ciencia e Ingeniería con JS</h2></center>
    <center><h2>Nombre: Valdez Gómez Nitcia Yazaret &nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. de control: 17091175</h2></center>
    </header>
    </section>


    <section id="problema"  class="gridProblema">
      <section id=descripcion>
            <center><h2>Problema</h2></center>
            <h1>Descripción:</h1>
            <p> ¿Cúal es la presion ejercida por una fuerza de 120N que actua sobre una superficie de 0.040 metros <br>
      </section>


<section id="datos">
<center><h2>Datos</h2></center>
<p>Fuerza = 120N <br>
Área: 0.40m al cuadrado <br>
   </p>               
</section>



<section id="formulas">
<center><h2>Fórmulas</h2></center><p>   P = F/A (Donde: P = presión, F = fuerza, A = área) <br>
            </p>
      </section>






<section id="solucion">
            <center><h2>Cálculos</h2></center>
   <p>  P=120/0.40</p>
</section>

<section id="resultado">
          <center><h2>Solución</h2></center>

        <div class=solution id="resultado1">
          <?php 
          $presion = $fuerza/ $area;

print "densidad =".$presion;
          ?>




        </div><br>
      </section>
    </section>
    <footer id="gridPie">
        <p>&copy; Solution Science Problems. 2019 Creative Commons 3.0</p>
    </footer>
</body>
</html>




